version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: blackonline-db
    environment:
      MYSQL_DATABASE: "blackonline_db"
      MYSQL_USER: "on"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: