version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: blackonline-db
    environment:
      MYSQL_DATABASE: blackonline_db
      MYSQL_USER: on
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: